### ISSUE TITLE
Initial api key from .env variable

### ISSUE THREAD

**Issue by AlexRabtsevich** [SKLINET/strapi-plugin-tinymce#11]
Hi I have a question about `apiKey` could we initialize it from env varibale such as by config, now we can it by admin panel, maybe we can it by config?

**Comment by Sklico** [comment]
Hi @AlexRabtsevich this way to provide API key is intentional, so anyone (client / editor / sitebuilder) can change it without need to change the code and .env, so we don't have any plans to change this.
