### ISSUE TITLE
[Media library] Upload image to media library by "drag on drop" or "ctrl v"

### ISSUE THREAD

**Issue by AlexRabtsevich** [SKLINET/strapi-plugin-tinymce#12]
Hi I didn't find any solution to use default media library upload by some event such as  `drag on drop` or `ctrl v` when we copy some image we store it as blob and maybe there are any solution to fix it. It is be better if we can use default `uploads` and after copied we save it to uploads and use link from upload such as `<img src="/uploads/[name].[format] />`

**Comment by AlexRabtsevich** [comment]
> Hi @AlexRabtsevich I don't understand what you exactly need. Where you want to drag n drop images ? There is Media Library from Strapi, so you can insert (upload / choose from library) images from there. From our point of view it's better solution to have images in Strapi so you can use them acrross the web instead of keep blobs directly in richtext without option to reuse that image. Our client often want this approach, because they work with Media Library and manage their assets there, so if Strapi has Media Library and we can use it, I don't see any benefits from changing this behaviour and pass images to richtext without storing them in Media Library. If you found some bug in inserting images to editor through Media Library, please let us know, but from your comment I don't exactly understand what would we fix.

I want to upload an image to the media library when I copy it from another location without clicking the `Media Library` button, in the plugin `CKEditor 5`  this function is available, maybe there is something like this

**Comment by Sklico** [comment]
Hi @AlexRabtsevich, it's not a bug and we not plan to work on this feature anytime soon. If you need it, feel free to fork our repository and maybe create PR with the feature.

Thanks
