### ISSUE TITLE
[Middlewares] Not access to fetch plugins,providers from marketplace

### ISSUE THREAD

**Issue by AlexRabtsevich** [SKLINET/strapi-plugin-tinymce#14]
Hi, when we add some changes in `middlewares.js` by documentation we don't have access to get any providers and plugins from strapi-marketplace, maybe we can fix it and edit readme 

![image](https://user-images.githubusercontent.com/47400952/195524785-0ac161f7-c245-4591-add2-6c4fb414927e.png)

**Comment by Sklico** [comment]
Hi @AlexRabtsevich, can you provide us your middleware.js config ? I don't know about anything in the config, that could cause this kind of error. What part is the problem one please ?

**Comment by AlexRabtsevich** [comment]
> 
I use config by README


![image](https://user-images.githubusercontent.com/47400952/195526888-89dc6ab2-0180-4a81-8d23-f549f639df7f.png)

**Comment by Sklico** [comment]
@AlexRabtsevich is there some error log in console (in DEV tools) ? The only one difference between your and our config is in quotes type. It could help if we can see some error log and check what the problem is. Thanks

**Comment by AlexRabtsevich** [comment]
> @AlexRabtsevich is there some error log in console (in DEV tools) ? The only one difference between your and our config is in quotes type. It could help if we can see some error log and check what the problem is. Thanks

![image](https://user-images.githubusercontent.com/47400952/195529508-b4aeb402-3600-43f5-9f89-0e3b2acbd40d.png)

**Comment by Sklico** [comment]
@AlexRabtsevich what version of Strapi do you use ?

**Comment by AlexRabtsevich** [comment]
> @AlexRabtsevich what version of Strapi do you use ?

We use `strapi 4.3.8` and here our dependencies

  "@sklinet/strapi-plugin-tinymce": "1.0.4",
    "@strapi/plugin-graphql": "4.3.8",
    "@strapi/plugin-i18n": "4.3.8",
    "@strapi/plugin-users-permissions": "4.3.8",
    "@strapi/strapi": "4.3.8",
    "@strapi/utils": "4.3.8",
    "lodash": "4.17.21",
    "mysql": "2.18.1",
    "patch-package": "6.4.7",
    "strapi-plugin-config-sync": "1.0.3",
    "strapi-plugin-passwordless": "4.0.8"

**Comment by AlexRabtsevich** [comment]
I think you should update `README` and use default strapi config + config which dependent to `tinymce`

Here is default config by strapi, maybe we can change default + add  current config
![image](https://user-images.githubusercontent.com/47400952/195565841-5bd0f130-f6ed-4b98-b88a-0366d3b5a734.png)

and I made some changes and here is my config

![image](https://user-images.githubusercontent.com/47400952/195567442-e53c7b8b-5439-4aa2-a1a0-0c5910bb09fb.png)

**Comment by Scientifica-2610** [comment]
i have same problem and errors

**Comment by Sklico** [comment]
Hey guys, we've updated README. We never mentioned that you should replace your config with our, just extend it and add tinymce specific part, this is the reason why it wasn't part of the readme. Anyway we've updated that, so I think it should resolve the problem.
