### ISSUE TITLE
TinyMCE doesn't show up

### ISSUE THREAD

**Issue by Drillan767** [SKLINET/strapi-plugin-tinymce#4]
Hello!

I'm using Strapi 4.4.0 on Node v14.20

I've installed the plugin, ran `yarn build` and set the API key in the configuration page, but I'm greeted with the following:

![image](https://user-images.githubusercontent.com/16261166/193251289-fb235106-a7ad-4300-bdae-4a265324c765.png)

Also, my `config/plugins.ts` file looks like so:

```js
module.exports = ({ env }) => ({
    tinymce: {
        enabled: true,
    },
    // other plugins

});
```

There are no info in the server console, and no error (related) in the browser console, so I don't really know where I should go from there... Any suggestion?

Thank you in advance

**Comment by Sklico** [comment]
Hi @Drillan767, check our readme please, I think you have a problem with CSP, so you should just update your config/middlewares.js file as we mentioned in README. 

Thanks

**Comment by Drillan767** [comment]
Well that was fast and working, thank you!
