### ISSUE TITLE
Tiny Editor API KEY issue - Strapi

### ISSUE THREAD

**Issue by SmitKakani7** [SKLINET/strapi-plugin-tinymce#40]
I have Tiny Editor's API key. 

Where I put the API key of the tiny editor. I am getting this error(image attached). due to this error, I can not able to use Editor. 

Anyone can Help!

I have attached package.json and Screenshot. 

Node version - 18.17.0
Starpi version - 4.20.0

**package.json** :
{
  "name": "cms",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@ckeditor/strapi-plugin-ckeditor": "^0.0.11",
    "@sklinet/strapi-plugin-tinymce": "^1.0.9",
    "@strapi/plugin-cloud": "4.20.0",
    "@strapi/plugin-graphql": "^4.20.0",
    "@strapi/plugin-i18n": "4.20.0",
    "@strapi/plugin-users-permissions": "4.20.0",
    "@strapi/provider-upload-aws-s3": "^4.24.0",
    "@strapi/strapi": "4.20.0",
    "better-sqlite3": "8.6.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "5.3.4",
    "strapi-plugin-publisher": "^1.5.7",
    "strapi-plugin-tagsinput": "^1.0.1",
    "styled-components": "5.3.3"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "544ed501-773f-4b1d-9c95-b3f7ef1e5356"
  },
  "engines": {
    "node": ">=18.0.0 <=20.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

![Screenshot 2024-05-13 161540](https://github.com/SKLINET/strapi-plugin-tinymce/assets/132330039/dfec3506-b797-4a55-8ddc-c947c6805876)

**Comment by anydaz** [comment]
Hi @SmitKakani7, I also encountered this issue before. I know it's been weeks already and perhaps you have already solve it, but, in case you haven't, I just want to let you know that you can input the API key in setting -> tinyMCE -> configuration

<img width="454" alt="image" src="https://github.com/SKLINET/strapi-plugin-tinymce/assets/43487866/b2c78f94-2127-4e5e-8846-f94fea147aef">
