### ISSUE TITLE
Use TinyMCE without the TinyMCE Cloud (Self-Hosted)

### ISSUE THREAD

**Issue by poberbeck** [SKLINET/strapi-plugin-tinymce#8]
It would be great if I could use TinyMCE Strapi plugin in the self-hosted varient ([https://www.tiny.cloud/blog/self-host-tinymce/](https://www.tiny.cloud/blog/self-host-tinymce/)).

**Comment by Sklico** [comment]
@poberbeck sorry, this version (with cloud) is intended as we use TinyMCE react component. We don't have any plans to support self-hosted version.

**Comment by sanneh2** [comment]
Why is this on the Strapi market if it's not a self-hosted solution? It doesn't make sense that this plugin would be approved on the Strapi official marketplace if the Editor is not using the Strapi server that is hosting it. There is a 1000 editor load limit per month and that adds up quickly for one user if there are multiple instances of Tiny. J reached 240 loads by using Strapi in 1 day. It's absurd, I don't understand why this is acceptable???

**Comment by Sklico** [comment]
@sanneh2 with all respect, this is not the right place to discuss this kind of questions. If you have any problem with our solution, just don't use it, feel free to make your own, or fork our repository and do any changes you want to do. If you have any problem with the fact that our plugin is accepted by Strapi, feel free to contact Strapi and ask them. Strapi as I know, doesn't have any limitations for using external services like TinyMCE cloud. It's the same as if we have any other plugin connected to any other third party service / library. If it's not ok for you and your needs, that's totally fine, no problem, this plugin is not for you and you just need something else. Please just respect our decision, we want to use official TinyMCE package (https://www.npmjs.com/package/@tinymce/tinymce-react). If there will be new TinyMCE version, we will need only to upgrade this one dependency and don't need to upgrade the whole TinyMCE and manage that self hosted version. This "issue" is closed, if you find some bugs, or you have some other proposals for enhancement, please make a new one. Just please, be respectful, if something is not good for you and don't cover your needs, it doesn't mean, that is not useful for anyone else.

Thanks and have nice day :)
